---
openapi: 3.1.0
components:
  schemas:
    CardDTO:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        imageUrl:
          type: string
        packId:
          type: string
    CardUploadForm:
      type: object
      properties:
        name:
          type: string
        packId:
          type: string
        image:
          type: string
          format: binary
    GameDTO:
      type: object
      properties:
        gameId:
          type: string
        gameState:
          type: string
        cards:
          type: array
          items:
            $ref: "#/components/schemas/CardDTO"
    GameStatusResponse:
      type: object
      properties:
        status:
          type: string
        correct:
          type: boolean
    PackDTO:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
paths:
  /card/create:
    put:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CardUploadForm"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardDTO"
      summary: Create Card
      tags:
        - Card Resource
  /game:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GameDTO"
      summary: Get All
      tags:
        - Game Resource
  /game/create:
    post:
      parameters:
        - name: packId
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameDTO"
      summary: Create Game
      tags:
        - Game Resource
  /game/{gameId}:
    delete:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
      summary: Delete Game
      tags:
        - Game Resource
  /game/{gameId}/player1/guess:
    post:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
        - name: cardId
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameStatusResponse"
      summary: Player 1 Guess
      tags:
        - Game Resource
  /game/{gameId}/player1/join:
    post:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardDTO"
      summary: Player 1 Join Game
      tags:
        - Game Resource
  /game/{gameId}/player2/guess:
    post:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
        - name: cardId
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameStatusResponse"
      summary: Player 2 Guess
      tags:
        - Game Resource
  /game/{gameId}/player2/join:
    post:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardDTO"
      summary: Player 2 Join Game
      tags:
        - Game Resource
  /game/{gameId}/reset:
    post:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameStatusResponse"
      summary: Reset Game
      tags:
        - Game Resource
  /game/{gameId}/start:
    post:
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameStatusResponse"
      summary: Start Game
      tags:
        - Game Resource
  /pack:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PackDTO"
      summary: Get All
      tags:
        - Pack Resource
  /pack/create:
    put:
      parameters:
        - name: packName
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackDTO"
      summary: Create Pack
      tags:
        - Pack Resource
  /pack/{id}/cards:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CardDTO"
      summary: Get Cards By Pack
      tags:
        - Pack Resource
info:
  title: qui-est-ce_back API
  version: "0.1"
servers:
  - url: http://localhost:8080
    description: Auto generated value
  - url: http://0.0.0.0:8080
    description: Auto generated value
