---
openapi: 3.1.0
paths:
  /card/create:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CardUploadForm"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardDTO"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Create Card
      tags:
      - Card Resource
      security:
      - SecurityScheme:
        - admin
  /card/{id}:
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Delete Card
      tags:
      - Card Resource
      security:
      - SecurityScheme:
        - admin
  /game:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GameDTO"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get All
      tags:
      - Game Resource
      security:
      - SecurityScheme: []
  /game/create:
    post:
      parameters:
      - name: packId
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameDTO"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Create Game
      tags:
      - Game Resource
      security:
      - SecurityScheme:
        - player
  /game/{gameId}:
    delete:
      parameters:
      - name: gameId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Delete Game
      tags:
      - Game Resource
      security:
      - SecurityScheme:
        - player
  /game/{gameId}/guess:
    post:
      parameters:
      - name: gameId
        in: path
        required: true
        schema:
          type: string
      - name: cardId
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameStatusResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Guess
      tags:
      - Game Resource
      security:
      - SecurityScheme:
        - player
  /game/{gameId}/join:
    post:
      parameters:
      - name: gameId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardDTO"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Join Game
      tags:
      - Game Resource
      security:
      - SecurityScheme:
        - player
  /game/{gameId}/reset:
    post:
      parameters:
      - name: gameId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameStatusResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Reset Game
      tags:
      - Game Resource
      security:
      - SecurityScheme:
        - player
  /game/{gameId}/start:
    post:
      parameters:
      - name: gameId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameStatusResponse"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Start Game
      tags:
      - Game Resource
      security:
      - SecurityScheme:
        - player
  /pack:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PackDTO"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get All
      tags:
      - Pack Resource
      security:
      - SecurityScheme: []
  /pack/create:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PackCreateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackDTO"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
        "400":
          description: Bad Request
      summary: Create Pack
      tags:
      - Pack Resource
      security:
      - SecurityScheme:
        - admin
  /pack/{id}:
    patch:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PackUpdateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackDTO"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Update Pack
      tags:
      - Pack Resource
      security:
      - SecurityScheme:
        - admin
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PackDTO"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get One
      tags:
      - Pack Resource
      security:
      - SecurityScheme: []
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Delete Pack
      tags:
      - Pack Resource
      security:
      - SecurityScheme:
        - admin
  /pack/{id}/cards:
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CardDTO"
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Get Cards By Pack
      tags:
      - Pack Resource
      security:
      - SecurityScheme: []
components:
  schemas:
    CardDTO:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        imageUrl:
          type: string
        packId:
          type: string
    CardUploadForm:
      type: object
      properties:
        name:
          type: string
        packId:
          type: string
        image:
          type: string
          format: binary
    GameDTO:
      type: object
      properties:
        gameId:
          type: string
        gameState:
          type: string
        cards:
          type: array
          items:
            $ref: "#/components/schemas/CardDTO"
    GameStatusResponse:
      type: object
      properties:
        status:
          type: string
        correct:
          type: boolean
    PackCreateRequest:
      type: object
      required:
      - packName
      properties:
        packName:
          type: string
          pattern: \S
          maxLength: 128
    PackDTO:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    PackUpdateRequest:
      type: object
      required:
      - packName
      properties:
        packName:
          type: string
          pattern: \S
          maxLength: 128
  securitySchemes:
    SecurityScheme:
      type: openIdConnect
      description: Authentication
info:
  title: qui-est-ce_back API
  version: "0.1"
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
